---
- include:  configure-bridge.yml
  when:     "'name' in libvirtd_bridge"

#- include:  configure-nat.yml
#  when:     "'name' in libvirtd_nat"

- include:  configure-lvm-disks.yml

- name: "Opening port {{ libvirtd_apache_port }} for dmz"
  firewalld:
    zone:       dmz
    port:       "{{ libvirtd_apache_port }}/tcp"
    permanent:  yes
    state:      enabled

- name: "Opening bridge on zone dmz"
  firewalld:
    zone:       dmz
    interface:  virbr0
    permanent:  yes
    state:      enabled
  register:     libvirtd_firewall_dmz
  notify:
    - libvirtd-reload-firewalld

## Serial communications setup
- name: Find tty group ID
  shell: set -o pipefail && egrep '^tty' /etc/group | awk -F':' '{ print $3 }'
  args:
    executable: /usr/bin/bash
  changed_when:
    - result.rc != 0
  register: tty_group

- name:   Ensure tty group has ID
  assert: that="{{ tty_group.stdout|trim|int }}"

- name: Alter pts for tty writable permissions, else you'll have no console
  lineinfile:
    dest:   /etc/fstab
    regexp: '^devpts\s+([^\s]+)\s+devpts\s+defaults((?:\s+\d){2}\s*)$'
    line:   'devpts{{ "\t" }}\1{{ "\t" }}devpts{{ "\t" }}defaults,gid={{ tty_group.stdout|trim }},mode=770\2'
    backrefs: yes
  register:   replaced_devpts
  notify:
    - libvirtd-remount-pts

- name: Sorting out nsswitch for libvirt
  lineinfile:
    path:   /etc/nsswitch.conf
    regexp: '(^(?!.*libvirt)hosts:\s+)(.+$)'
    line: '\1libvirt \2'
    backrefs: yes
    state:  present
