---
- name:   "Get the CentOS ISO to use locally"
  synchronize:
    src:  "{{ libvirt_install.url }}"
    dest: "{{ libvirt_install.iso }}"
    partial:  yes
    mode: pull
  delegate_to: "{{ inventory_hostname }}"
  register: libvirt_new_iso

- name:   "Set ISO permissions"
  file:
    path: "{{ libvirt_install.iso }}"
    mode: "0644"
    owner:  qemu
    group:  qemu
  when:   libvirt_new_iso|changed

#TODO: - name:   "Create kickstarts"
#TODO:  use machine ip / hostname in kickstart
- name:   "Create kickstarts for all machines"
  template:
    src:    var/www/html/kickstart.j2
    dest:   /var/www/html/{{ item.key }}.ks
    mode:   0644
  with_dict: "{{ libvirt_machines }}"

#TODO: - name:   "Host kickstarts"

- name:   "Create virtual machines"
  command: >
      /bin/virt-install
        --name "{{ item.key }}"
        --memory "{{ item.value.memory }}"
        --vcpus "{{ item.value.vcpus }}"
        --cpu host
        --autostart
        --location "{{ libvirt_install.iso }}"
        --disk "{{ item.value.disk }}"
        --network bridge=virbr0
        --graphics none
        -v --extra-args "net.ifnames=0 ks=http://192.168.122.1/{{ item.key }}.ks console=ttyS0"
        {{ item.value.public|default(None) }}
  args:
    chdir:    /var/lib/libvirt
    creates:  "/etc/libvirt/qemu/{{ item.key }}.xml"
  with_dict: "{{ libvirt_machines }}"
  when: libvirtd_create_machines

# TODO: Accept EULA to finish automated install
