---
- name:   "Get the CentOS ISO to use locally"
  stat:
    path: "{{ libvirtd_install.dest }}"
  register: libvirtd_iso_dest

- name:   "Get the CentOS ISO to use locally"
  get_url:
    url:  "{{ libvirtd_install.url }}"
    dest: "{{ libvirtd_install.dest }}"
#synchronize:
#    partial:  yes
#    mode: pull
  delegate_to: "{{ inventory_hostname }}"
  when:   not libvirtd_iso_dest.stat.exists

- name:   "Set ISO permissions"
  file:
    path: "{{ libvirtd_install.dest }}"
    mode: "0644"
    owner:  qemu
    group:  qemu

- name:   "Create kickstarts for all machines"
  template:
    src:    var/www/html/kickstart.j2
    dest:   /var/www/html/{{ item.key }}.ks
    mode:   0644
  with_dict: "{{ libvirtd_machines }}"

# BUGFIX: Need to detach from this console
#       /bin/virt-install \
#         --name "data" \
#         --memory 2048 \
#         --vcpus 2 \
#         --cpu host \
#         --autostart \
#         --location "/tmp/CentOS-7-x86_64-Minimal-2003.iso" \
#         --disk /dev/vmsVG/data \
#         --graphics none \
#         -v --extra-args "net.ifnames=0 ks=http://192.168.122.1/data.ks console=ttyS0 text" \
#         --network bridge=virbr0

- name:   "Create virtual machines"
  command: >
      /bin/virt-install
        --name "{{ item.key }}"
        --memory "{{ item.value.memory }}"
        --vcpus "{{ item.value.vcpus }}"
        --cpu host
        --autostart
        --location "{{ libvirtd_install.dest }}"
        --disk "{{ item.value.disk }}"
        --graphics none --noautoconsole
        -v --extra-args "net.ifnames=0 ks=http://{{ ansible_facts[item.value.bridge]['ipv4']['address'] }}:{{ libvirtd_apache_port }}/{{ item.key }}.ks console=ttyS0 text"
        --network bridge="{{ item.value.bridge }}"
  args:
    chdir:    /var/lib/libvirt
    creates:  "/etc/libvirt/qemu/{{ item.key }}.xml"
  with_dict: "{{ libvirtd_machines }}"
  when: libvirtd_create_machines

- name:   "Start machines"
  virt:
    name:   "{{ item.key }}"
    state:  "running"
    autostart:  yes
    command:  "start"
  with_dict:  "{{ libvirtd_machines }}"
