---
- include:  install.yml
  tags:
    - install
    - libvirtd
- include:  configure.yml
  tags:
    - configure
    - network
    - libvirtd
  when: libvirtd_configure
- include:  machines.yml
  tags:
    - machines
    - libvirtd
  when: libvirtd_create_machines
